import vocab from './vocab.json';

/** Lookups over the bundled schema.org vocabulary (generated by scripts/build-vocab.ts). */
interface TypeInfo { parents: string[]; layer?: string; supersededBy?: string; enumeration?: true }
interface PropInfo { domains: string[]; ranges: string[]; layer?: string; supersededBy?: string }

const TYPES = vocab.types as Record<string, TypeInfo>;
const PROPS = vocab.properties as Record<string, PropInfo>;
const MEMBERS = vocab.members as Record<string, string[]>;
const own = (o: object, k: string) => Object.prototype.hasOwnProperty.call(o, k);

export const isType = (name: string) => own(TYPES, name);
export const isProperty = (name: string) => own(PROPS, name);
export const typeNames = () => Object.keys(TYPES);
export const propertyNames = () => Object.keys(PROPS);
export const domains = (prop: string) => (isProperty(prop) ? PROPS[prop].domains : []);
export const ranges = (prop: string) => (isProperty(prop) ? PROPS[prop].ranges : []);
export const isEnumeration = (type: string) => isType(type) && !!TYPES[type].enumeration;

const ancestorCache = new Map<string, string[]>();
/** The type itself plus its transitive parents, breadth-first (nearest first). */
export function ancestors(type: string): string[] {
  let out = ancestorCache.get(type);
  if (out) return out;
  out = [type];
  for (let i = 0; i < out.length; i++) {
    for (const p of isType(out[i]) ? TYPES[out[i]].parents : []) if (!out.includes(p)) out.push(p);
  }
  ancestorCache.set(type, out);
  return out;
}

/** Whether any of the types, or any of their ancestors, is in the property's domains. */
export function propertyAllowedOn(prop: string, types: string[]): boolean {
  const ds = domains(prop);
  return types.some((t) => ancestors(t).some((a) => ds.includes(a)));
}

let children: Map<string, string[]> | undefined;
const memberCache = new Map<string, string[]>();
/** Members of an enumeration, including members of its sub-enumerations. */
export function enumMembers(type: string): string[] {
  let out = memberCache.get(type);
  if (out) return out;
  if (!children) {
    children = new Map();
    for (const [name, t] of Object.entries(TYPES)) for (const p of t.parents) children.set(p, [...(children.get(p) ?? []), name]);
  }
  out = [];
  if (isEnumeration(type)) {
    const queue = [type];
    for (let i = 0; i < queue.length; i++) {
      if (own(MEMBERS, queue[i])) out.push(...MEMBERS[queue[i]]);
      for (const c of children.get(queue[i]) ?? []) if (!queue.includes(c)) queue.push(c);
    }
  }
  memberCache.set(type, out);
  return out;
}

export function deprecation(term: string): { supersededBy?: string; attic?: boolean } | null {
  const info = isType(term) ? TYPES[term] : isProperty(term) ? PROPS[term] : undefined;
  if (!info) return null;
  if (info.supersededBy) return { supersededBy: info.supersededBy };
  if (info.layer === 'attic') return { attic: true };
  return null;
}

function levenshtein(a: string, b: string, max: number): number {
  if (Math.abs(a.length - b.length) > max) return max + 1;
  let prev = Array.from({ length: b.length + 1 }, (_, j) => j);
  for (let i = 1; i <= a.length; i++) {
    const cur = [i];
    let best = i;
    for (let j = 1; j <= b.length; j++) {
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
      best = Math.min(best, cur[j]);
    }
    if (best > max) return max + 1;
    prev = cur;
  }
  return prev[b.length];
}

/**
 * Closest candidate, compared case-insensitively: within distance 2, or 1 for
 * names of 4 characters or fewer. An exact case-insensitive match always wins.
 */
export function suggest(name: string, candidates: Iterable<string>): string | undefined {
  const lower = name.toLowerCase();
  const max = name.length <= 4 ? 1 : 2;
  let best: string | undefined;
  let bestDist = max + 1;
  for (const c of candidates) {
    const cl = c.toLowerCase();
    if (cl === lower) return c;
    const d = levenshtein(lower, cl, max);
    if (d < bestDist) {
      best = c;
      bestDist = d;
    }
  }
  return best;
}
