import { readFileSync, writeFileSync } from 'node:fs';
import { JSDOM } from 'jsdom';
const dom = new JSDOM(readFileSync(new URL('./fixture.html', import.meta.url), 'utf8'), { url: 'https://ex.com/p', runScripts: 'outside-only' });
const page = dom.window.eval(readFileSync(new URL('../public/extract.js', import.meta.url), 'utf8'));
writeFileSync(new URL('../src/demo.ts', import.meta.url),
  `// Generated by test/make-demo.ts — sample data for running the UI outside Firefox (npx vite).\nimport type { PageData } from './lib/types';\n\nexport const DEMO_PAGE: PageData = ${JSON.stringify(page, null, 2)};\n`);
