// Generated by test/make-demo.ts — sample data for running the UI outside Firefox (npx vite).
import type { PageData } from './lib/types';

export const DEMO_PAGE: PageData = {
  "url": "https://ex.com/p",
  "title": "Fixture",
  "blocks": [
    {
      "source": "json-ld",
      "index": 0,
      "raw": "\n{\"@context\":\"https://schema.org\",\"@graph\":[\n {\"@type\":\"MedicalClinic\",\"@id\":\"https://ex.com/#org\",\"name\":\"Ex Clinic\",\"url\":\"https://ex.com/\",\"logo\":{\"@type\":\"ImageObject\",\"url\":\"https://ex.com/logo.png\"},\"address\":{\"@id\":\"https://ex.com/#addr\"}},\n {\"@type\":\"PostalAddress\",\"@id\":\"https://ex.com/#addr\",\"streetAddress\":\"1 Main\",\"addressLocality\":\"Richmond\"},\n {\"@type\":\"WebPage\",\"@id\":\"https://ex.com/p#webpage\",\"isPartOf\":{\"@id\":\"https://ex.com/#website\"},\"publisher\":{\"@id\":\"https://ex.com/#org\"},\"datePublished\":\"May 3 2024\"}\n]}\n",
      "data": {
        "@context": "https://schema.org",
        "@graph": [
          {
            "@type": "MedicalClinic",
            "@id": "https://ex.com/#org",
            "name": "Ex Clinic",
            "url": "https://ex.com/",
            "logo": {
              "@type": "ImageObject",
              "url": "https://ex.com/logo.png"
            },
            "address": {
              "@id": "https://ex.com/#addr"
            }
          },
          {
            "@type": "PostalAddress",
            "@id": "https://ex.com/#addr",
            "streetAddress": "1 Main",
            "addressLocality": "Richmond"
          },
          {
            "@type": "WebPage",
            "@id": "https://ex.com/p#webpage",
            "isPartOf": {
              "@id": "https://ex.com/#website"
            },
            "publisher": {
              "@id": "https://ex.com/#org"
            },
            "datePublished": "May 3 2024"
          }
        ]
      }
    },
    {
      "source": "json-ld",
      "index": 1,
      "raw": "{\"@context\":\"https://schema.org\",\"@type\":\"Product\",\"name\":\"Widget\",\"offers\":{\"@type\":\"Offer\",\"price\":\"$1,299\",\"priceCurrency\":\"usd\"}}",
      "data": {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": "Widget",
        "offers": {
          "@type": "Offer",
          "price": "$1,299",
          "priceCurrency": "usd"
        }
      }
    },
    {
      "source": "json-ld",
      "index": 2,
      "raw": "{ \"@type\": \"Thing\", bad json }",
      "error": "Expected double-quoted property name in JSON at position 20 (line 1 column 21)"
    },
    {
      "source": "microdata",
      "index": 0,
      "data": {
        "@context": "https://schema.org",
        "@type": "Person",
        "name": "Jane Doe",
        "address": {
          "@type": "PostalAddress",
          "addressLocality": "Houston"
        },
        "url": "https://ex.com/jane"
      }
    },
    {
      "source": "rdfa",
      "index": 0,
      "data": {
        "@context": "https://schema.org",
        "@type": "Event",
        "name": "Meetup",
        "startDate": "2026-11-01T18:00",
        "location": {
          "@type": "Place",
          "name": "Library"
        }
      }
    }
  ]
};
